export const technologies = {
  comfort: [
    'HTML5',
    'CSS3 / Less / Sass / Scss',
    'Materializecss / Bootstrap / Vuetify',
    'JavaScript / TypeScript',
    'VueJS',
    'NuxtJS',
    'Vuex',
    'ReactJS',
    'NextJS',
    'Redux',
    'Redux Toolkit',
    'Git',
    'Webpack',
    'Photoshop / Figma / Zeplin',
  ],
  experience: [
    'NodeJS',
    'ExpressJS',
    'MongoDB',
    'Firebase',
    'Jest / React-testing-library',
    'Atlassian Jira / Dropbox / Clickup',
  ],
};
